### ISSUE TITLE
Anaconda Extensions for Jupyter 4.2 blog post

### ISSUE THREAD

**Issue by ijstokes** [Anaconda-Platform/anaconda-nb-extensions#158] opened 2016-04-12 13:55 UTC
We need a blog post that highlights new Jupyter extensions based on the 4.2 extension configuration structure, possibly showing off the new extension construction functionality (in fact, that is probably two blog posts: one for extension users, one for extension developers).

**Comment by stephenakearns** [comment] 2016-07-19 12:37
duplicate of #159  - closing this one.

**Closed by stephenakearns** 2016-07-19 12:37 UTC
